node {
    
    def WORKSPACE = pwd()
   // Mark the code checkout 'stage'....
   stage 'Checkout'

   // Checkout code from repository
   checkout scm

   // Get the maven tool.
   // ** NOTE: This 'M3' maven tool must be configured
   // **       in the global configuration.
   def mvnHome = tool 'maven'

   // Mark the code build 'stage'....
   stage 'Maven Build'
   // Run the maven build
   sh "cd projects/brms-coolstore-demo && ${mvnHome}/bin/mvn -Dmaven.test.failure.ignore clean install"
   
   step([$class: 'ArtifactArchiver', artifacts: '**/target/*.war', fingerprint: true])
   //step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
   
   stage 'OpenShift Build'
   
   // Download support script
   sh "mkdir -p ${WORKSPACE}/build-tools && curl -s -o ${WORKSPACE}/build-tools/ose-monitor.sh https://raw.githubusercontent.com/sabre1041/ose3-samples/master/trigger-monitor-build.sh && chmod +x ${WORKSPACE}/build-tools/ose-monitor.sh"
   

    withCredentials([[$class: 'StringBinding',
            credentialsId: 'bdd-ose-token', variable: 'OSE_TOKEN']]) {
                
                sh "${WORKSPACE}/build-tools/ose-monitor.sh -h=${OPENSHIFT_HOST} -t=${env.OSE_TOKEN} -n=${OPENSHIFT_PROJECT} -a=${OPENSHIFT_APPLICATION}"
            
        }

}
